package com.example.curingdunning.dto;

// OrderResponse.java (in your DTO package)


import java.math.BigDecimal;

import lombok.Data;

@Data
public class OrderResponse {
    private String orderId;    // The ID generated by Razorpay (e.g., 'order_MizK5v131F2J3x')
    private Long billId;       // Original bill ID, carried forward
    private BigDecimal amount;
    private String keyId;      // Your Razorpay Test Key ID (public key)

    // Constructors, Getters, and Setters
}